### ISSUE TITLE
Create SignIn and SignUp Screen

### ISSUE THREAD

**Issue by oybekjon94** [oybekjon94/e-commerce#2]

**Comment by khurshiddev** [comment]
I will work this

**Comment by oybekjon94** [comment]
okay brother fighting

**Comment by oybekjon94** [comment]
brother please first create new branch from develop on your android studio

**Comment by oybekjon94** [comment]
don't forget please

**Comment by khurshiddev** [comment]
ok my bro

**Comment by behzodhalil** [comment]
Hey, @oybekjon94 @khurshiddev 

How is progressing now? Have you finished these screens?

Thanks!

**Comment by oybekjon94** [comment]
Hey, @behzodhalil 
@khurshiddev is creating this screen. I think it will probably be over by the end of the week.

**Comment by oybekjon94** [comment]
@khurshiddev please let's finish it by the end of the week. Otherwise we will pay a fine 😅

**Comment by khurshiddev** [comment]
Hey, i finished sign_in screen please check

**Comment by khurshiddev** [comment]
Hey, brother's i finished sign_in screen and back and please check

**Comment by oybekjon94** [comment]
Aha okay thank you
